# Security Policies Configuration
# Comprehensive security policies for Python upgrade automation

security_policies:
  # Vulnerability Management
  vulnerability_management:
    severity_thresholds:
      critical: 0    # No critical vulnerabilities allowed
      high: 2        # Maximum 2 high severity issues
      medium: 5      # Maximum 5 medium severity issues
      low: 10        # Maximum 10 low severity issues
    
    scan_frequency:
      dependencies: "daily"
      code: "on_commit"
      infrastructure: "weekly"
    
    remediation_sla:
      critical: "24_hours"
      high: "7_days"
      medium: "30_days"
      low: "90_days"

  # Code Security Standards
  code_security:
    required_tools:
      - "bandit"      # Python security linter
      - "safety"      # Dependency vulnerability scanner
      - "semgrep"     # Static analysis security scanner
    
    prohibited_patterns:
      - "eval()"
      - "exec()"
      - "subprocess.call(shell=True)"
      - "pickle.loads()"
      - "yaml.load()"
    
    required_practices:
      - "input_validation"
      - "output_encoding"
      - "secure_random"
      - "proper_exception_handling"
      - "logging_security_events"

  # Dependency Management
  dependency_security:
    allowed_sources:
      - "pypi.org"
      - "internal_registry"
    
    update_policy:
      security_patches: "immediate"
      minor_versions: "monthly"
      major_versions: "quarterly_review"
    
    license_compliance:
      allowed_licenses:
        - "MIT"
        - "Apache-2.0"
        - "BSD-3-Clause"
        - "ISC"
      prohibited_licenses:
        - "GPL-3.0"
        - "AGPL-3.0"
        - "SSPL-1.0"

  # Access Control
  access_control:
    authentication:
      mfa_required: true
      session_timeout: "8_hours"
      password_policy: "strong"
    
    authorization:
      principle: "least_privilege"
      review_frequency: "quarterly"
      emergency_access: "break_glass_procedure"

  # Audit and Compliance
  audit_compliance:
    logging_requirements:
      - "authentication_events"
      - "authorization_failures"
      - "data_access"
      - "configuration_changes"
      - "security_events"
    
    retention_policy:
      security_logs: "2_years"
      audit_trails: "7_years"
      access_logs: "1_year"
    
    compliance_frameworks:
      - "SOC2_Type2"
      - "ISO27001"
      - "NIST_Cybersecurity_Framework"

  # Incident Response
  incident_response:
    severity_levels:
      p0: "critical_security_breach"
      p1: "high_impact_vulnerability"
      p2: "medium_impact_issue"
      p3: "low_impact_concern"
    
    response_times:
      p0: "15_minutes"
      p1: "1_hour"
      p2: "4_hours"
      p3: "24_hours"
    
    escalation_procedures:
      - "security_team_notification"
      - "management_escalation"
      - "external_communication"
      - "regulatory_reporting"

  # Secure Development
  secure_development:
    code_review:
      required_reviewers: 2
      security_review_required: true
      automated_scanning: true
    
    testing_requirements:
      unit_test_coverage: 80
      security_test_coverage: 90
      penetration_testing: "quarterly"
    
    deployment_security:
      environment_isolation: true
      secrets_management: "vault_required"
      infrastructure_as_code: true